### ISSUE TITLE
상품 메인 랜딩 페이지 구현

### ISSUE THREAD

**Issue by page1597** [page1597/commerce#16]
## Description
상품 메인 렌딩 페이지 구현

## To-do
- [x] 카테고리별 상품들을 4개씩 보여주는 페이지 설계
- [x] 각 카테고리 옆 “더보기” 버튼을 통해 해당 카테고리의 상품 페이지로 이동
- [x] 각 상품에는 제품명, 사진, 가격, 카테고리 정보를 표시
- [x] 제품 사진이 여러 장일 경우, 캐러셀(carousel) 기능
