### ISSUE TITLE
코드 정리

### ISSUE THREAD

**Issue by page1597** [page1597/commerce#95]
## Description
코드 정리 및 리팩토링 사항

## To-do
- [ ] 쓸데없는 주석 제거
- [ ] 커스텀 Alert 코드 정리하기
- [ ] 기능 알아보기 쉽게 주석 추가
- [ ] 모듈화
- [ ] 폼 관련 코드 정리하기
